
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
spring:
  profiles:
    active: dev
  application:
    name: model-client
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse
    username: root
    password: liuduo2001
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-handlers-package: com.example.spring.entity


